baseURL: "https://aiyush-g.github.io/PublicationsWebsite/"
languageCode: "en-us"
title: "AGSB Publications Committee"
pygmentsstyle: "monokai"

theme: hugo-theme-novela
paginate: 6

social:
  twitter: "#"
  github: "#"
  instagram: "#"
  linkedin: "#"
  dribbble: "#"
  youtube: "#"
  
taxonomies:
  authors:
    - Aiyush Gupta
    - Publications
    - EOY 2021

