baseURL: "https://aiyush-g.github.io/PublicationsWebsite/"
languageCode: "en-us"
title: "Hugo Novela"
pygmentsstyle: "monokai"

theme: hugo-theme-novela
paginate: 6
social:
  twitter: "FrankTLDR"
  github: "DirtyF"
taxonomies:
  author: authors

